# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup and execute Gradle 'build' task
      uses: gradle/gradle-build-action@v2.1.5
      with:
        arguments: build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Grails-Plugin-${{ github.ref_name }}-${{ github.sha }}
        path: build/libs/sequential-commands-plugin-${{ github.ref_name }}-${{ github.sha }}.jar
